export Main from './Repo/Main/Main'
export Sidebar from './Repo/Sidebar/Sidebar'
export Tabs from './Repo/Tabs/Tabs'
export Footer from './Repo/Footer/Footer'
export OpenFiles from './Repo/OpenFiles/OpenFiles'
export Directory from './Repo/Directory/Directory'
export Folder from './Repo/Folder/Folder'
export File from './Repo/File/File'
